### ISSUE TITLE
能把我拉进我们这个contributer里面吗老马 我这面试项目经历写了我们项目 我刚发现没我了：）

### ISSUE THREAD

**Issue by Klsolin** [xmmmmmovo/TaixuEngine#230]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xmmmmmovo** [comment]
有你哇，这事儿在微信上说就行

**Comment by Klsolin** [comment]
ok 刚才没看到我😭

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: xmmmmmovo ***@***.***>
发送时间: Tuesday, April 16, 2024 3:51:25 PM
收件人: xmmmmmovo/TaixuEngine ***@***.***>
抄送: Jiaqi Xie [ml21j2x] ***@***.***>; Author ***@***.***>
主题: Re: [xmmmmmovo/TaixuEngine] 能把我拉进我们这个contributer里面吗老马 我这面试项目经历写了我们项目 我刚发现没我了：） (Issue #230)


CAUTION: External Message. Use caution opening links and attachments.

Closed #230<https://github.com/xmmmmmovo/TaixuEngine/issues/230> as completed.
